# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0002_auto_20161005_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
