# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0005_auto_20161011_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
    ]
