# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0008_auto_20161011_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
