# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0009_auto_20161011_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
