# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0010_clothes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='stocks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
